### ISSUE TITLE
Remove .babelrc from published package

### ISSUE THREAD

**Issue by flybayer** [drenglish/vue-match-media#1]
Hey, thanks for this library! It works great!

I did have one big hiccup getting it to work for me on IE11 because I couldn't get it to transpile to ES5.

The reason is `babel-loader` was picking up the `.babelrc` in this package which was overriding my own babel config.

My current workaround is documented here: https://github.com/webpack/webpack/issues/2902#issuecomment-315796888

**Comment by drenglish** [comment]
Ouch -- sorry for inadvertently being a timewaster, and thanks for the heads-up. I'll fix that.

**Comment by drenglish** [comment]
Added .npmignore to suppress unnecessary config from NPM published package. Bumped to 1.0.1.
