### ISSUE TITLE
Build errors with webpack

### ISSUE THREAD

**Issue by solidevolution** [drenglish/vue-match-media#7]
The plugin works fine in development but we get an error while building the dist package:

`ERROR in static/js/vendor.6853556982bacdd7ab35.js from UglifyJs
Invalid assignment [./~/vue-match-media/src/index.js:7,0][static/js/vendor.6853556982bacdd7ab35.js:47813,72]`

Here our development package.json:

{
  "name": "secret",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "node build/build.js",
    "lint": "eslint --ext .js,.vue src",
    "test": "./node_modules/.bin/jest --no-cache --coverage"
  },
  "dependencies": {
    ...
    "vue-match-media": "^1.0.2"
    ...
  },
  "devDependencies": {
    "autoprefixer": "^7.1.6",
    "axios-mock-adapter": "^1.10.0",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-jest": "^20.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^2.3.0",
    "connect-history-api-fallback": "^1.5.0",
    "copy-webpack-plugin": "^4.2.3",
    "css-loader": "^0.28.0",
    "cssnano": "^3.10.0",
    "eslint": "^3.19.0",
    "eslint-config-standard": "^6.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-html": "^3.0.0",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^2.0.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.16.2",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.11.1",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "jest": "^20.0.4",
    "jest-vue-preprocessor": "^1.3.1",
    "jsdom": "^11.5.1",
    "json-loader": "^0.5.7",
    "json-server": "^0.12.1",
    "opn": "^5.1.0",
    "optimize-css-assets-webpack-plugin": "^2.0.0",
    "ora": "^1.2.0",
    "postcss-color-function": "^4.0.1",
    "postcss-cssnext": "^3.0.2",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^2.0.9",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "stylelint": "^8.3.0",
    "stylelint-config-standard": "^17.0.0",
    "stylelint-order": "^0.6.0",
    "stylelint-processor-html": "^1.0.0",
    "stylelint-webpack-plugin": "^0.9.0",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.5.0",
    "vue-server-renderer": "^2.5.8",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.8",
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-dev-middleware": "^1.12.1",
    "webpack-hot-middleware": "^2.21.0",
    "webpack-merge": "^4.1.1"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "jest": {
    "verbose": true,
    "collectCoverageFrom": [
      "src/components/*.vue",
      "src/services/*.js",
      "src/store/modules/*.js"
    ],
    "roots": [
      "<rootDir>/src"
    ],
    "moduleFileExtensions": [
      "js",
      "vue"
    ],
    "moduleDirectories": [
      "node_modules"
    ],
    "moduleNameMapper": {
      "^vue$": "vue/dist/vue.common.js",
      "src/([^\\.]*)$": "<rootDir>/src/$1",
      "@/([^\\.]*)$": "<rootDir>/src/$1"
    },
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
      ".*\\.vue$": "<rootDir>/node_modules/jest-vue-preprocessor"
    },
    "transformIgnorePatterns": [
      "node_modules/(?!vue-router)"
    ]
  }
}

**Comment by solidevolution** [comment]
@drenglish any news here?

**Comment by solidevolution** [comment]
Dead repo

**Comment by morrislaptop** [comment]
hi @solidevolution , you need to transform this module in your webpack config.

**Comment by morrislaptop** [comment]
I might switch to AlexandreBonaventure/vue-mq

**Comment by solidevolution** [comment]
@morrislaptop thank you but I needed a solution which can simply use my postcss media queries.
Did it myself now. Use less vendor libraries!
